# Generated by Django 2.2.16 on 2023-04-10 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20230405_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='cooking_time',
            new_name='coocking_time',
        ),
    ]
